<a href="https://colab.research.google.com/github/noorchawla/big-data-_assignments/blob/main/Labeval_MCA1_202302022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
multiply the following matrices and also find covariance between matrics using Numpy : p=[[1,2],[2,3]]q=[[4,5],[6,7]]



In [3]:
import numpy as np

# Define matrices
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

# Multiply matrices
product = np.dot(p, q)
print("Matrix Product:")
print(product)

# Calculate covariance
covariance = np.cov(p,q)
print("\nCovariance between matrices:")
print(covariance)

Matrix Product:
[[16 19]
 [26 31]]

Covariance between matrices:
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
